# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.v1_users_self_put200_response import V1UsersSelfPut200Response

class TestV1UsersSelfPut200Response(unittest.TestCase):
    """V1UsersSelfPut200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1UsersSelfPut200Response:
        """Test V1UsersSelfPut200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1UsersSelfPut200Response`
        """
        model = V1UsersSelfPut200Response()
        if include_optional:
            return V1UsersSelfPut200Response(
                item = homebox_client.models.repo/user_update.repo.UserUpdate(
                    email = '', 
                    name = '', )
            )
        else:
            return V1UsersSelfPut200Response(
        )
        """

    def testV1UsersSelfPut200Response(self):
        """Test V1UsersSelfPut200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
