# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.authroles_role import AuthrolesRole

class TestAuthrolesRole(unittest.TestCase):
    """AuthrolesRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthrolesRole(self):
        """Test AuthrolesRole"""
        # inst = AuthrolesRole()

if __name__ == '__main__':
    unittest.main()
