# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_attachment import EntAttachment

class TestEntAttachment(unittest.TestCase):
    """EntAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntAttachment:
        """Test EntAttachment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntAttachment`
        """
        model = EntAttachment()
        if include_optional:
            return EntAttachment(
                created_at = '',
                edges = homebox_client.models.ent/attachment_edges.ent.AttachmentEdges(
                    item = homebox_client.models.item.item(), 
                    thumbnail = homebox_client.models.thumbnail.thumbnail(), ),
                id = '',
                mime_type = '',
                path = '',
                primary = True,
                title = '',
                type = 'attachment',
                updated_at = ''
            )
        else:
            return EntAttachment(
        )
        """

    def testEntAttachment(self):
        """Test EntAttachment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
