# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.api.labels_api import LabelsApi


class TestLabelsApi(unittest.TestCase):
    """LabelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LabelsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_labels_get(self) -> None:
        """Test case for v1_labels_get

        Get All Labels
        """
        pass

    def test_v1_labels_id_delete(self) -> None:
        """Test case for v1_labels_id_delete

        Delete Label
        """
        pass

    def test_v1_labels_id_get(self) -> None:
        """Test case for v1_labels_id_get

        Get Label
        """
        pass

    def test_v1_labels_id_put(self) -> None:
        """Test case for v1_labels_id_put

        Update Label
        """
        pass

    def test_v1_labels_post(self) -> None:
        """Test case for v1_labels_post

        Create Label
        """
        pass


if __name__ == '__main__':
    unittest.main()
