# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_notifier_edges import EntNotifierEdges

class TestEntNotifierEdges(unittest.TestCase):
    """EntNotifierEdges unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntNotifierEdges:
        """Test EntNotifierEdges
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntNotifierEdges`
        """
        model = EntNotifierEdges()
        if include_optional:
            return EntNotifierEdges(
                group = homebox_client.models.ent/group.ent.Group(
                    created_at = '', 
                    currency = '', 
                    edges = homebox_client.models.edges.edges(), 
                    id = '', 
                    name = '', 
                    updated_at = '', ),
                user = homebox_client.models.ent/user.ent.User(
                    activated_on = '', 
                    created_at = '', 
                    edges = homebox_client.models.edges.edges(), 
                    email = '', 
                    id = '', 
                    is_superuser = True, 
                    name = '', 
                    role = homebox_client.models.role.role(), 
                    superuser = True, 
                    updated_at = '', )
            )
        else:
            return EntNotifierEdges(
        )
        """

    def testEntNotifierEdges(self):
        """Test EntNotifierEdges"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
