# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.v1_change_password import V1ChangePassword

class TestV1ChangePassword(unittest.TestCase):
    """V1ChangePassword unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ChangePassword:
        """Test V1ChangePassword
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ChangePassword`
        """
        model = V1ChangePassword()
        if include_optional:
            return V1ChangePassword(
                current = '',
                new = ''
            )
        else:
            return V1ChangePassword(
        )
        """

    def testV1ChangePassword(self):
        """Test V1ChangePassword"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
