# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.v1_group_invitation_create import V1GroupInvitationCreate

class TestV1GroupInvitationCreate(unittest.TestCase):
    """V1GroupInvitationCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GroupInvitationCreate:
        """Test V1GroupInvitationCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GroupInvitationCreate`
        """
        model = V1GroupInvitationCreate()
        if include_optional:
            return V1GroupInvitationCreate(
                expires_at = '',
                uses = 1
            )
        else:
            return V1GroupInvitationCreate(
                uses = 1,
        )
        """

    def testV1GroupInvitationCreate(self):
        """Test V1GroupInvitationCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
