# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.v1_group_invitation import V1GroupInvitation

class TestV1GroupInvitation(unittest.TestCase):
    """V1GroupInvitation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GroupInvitation:
        """Test V1GroupInvitation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GroupInvitation`
        """
        model = V1GroupInvitation()
        if include_optional:
            return V1GroupInvitation(
                expires_at = '',
                token = '',
                uses = 56
            )
        else:
            return V1GroupInvitation(
        )
        """

    def testV1GroupInvitation(self):
        """Test V1GroupInvitation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
