# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.api.notifiers_api import NotifiersApi


class TestNotifiersApi(unittest.TestCase):
    """NotifiersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotifiersApi()

    def tearDown(self) -> None:
        pass

    def test_v1_notifiers_get(self) -> None:
        """Test case for v1_notifiers_get

        Get Notifiers
        """
        pass

    def test_v1_notifiers_id_delete(self) -> None:
        """Test case for v1_notifiers_id_delete

        Delete a Notifier
        """
        pass

    def test_v1_notifiers_id_put(self) -> None:
        """Test case for v1_notifiers_id_put

        Update Notifier
        """
        pass

    def test_v1_notifiers_post(self) -> None:
        """Test case for v1_notifiers_post

        Create Notifier
        """
        pass

    def test_v1_notifiers_test_post(self) -> None:
        """Test case for v1_notifiers_test_post

        Test Notifier
        """
        pass


if __name__ == '__main__':
    unittest.main()
