# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_item_field import EntItemField

class TestEntItemField(unittest.TestCase):
    """EntItemField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntItemField:
        """Test EntItemField
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntItemField`
        """
        model = EntItemField()
        if include_optional:
            return EntItemField(
                boolean_value = True,
                created_at = '',
                description = '',
                edges = homebox_client.models.ent/item_field_edges.ent.ItemFieldEdges(
                    item = homebox_client.models.item.item(), ),
                id = '',
                name = '',
                number_value = 56,
                text_value = '',
                time_value = '',
                type = 'text',
                updated_at = ''
            )
        else:
            return EntItemField(
        )
        """

    def testEntItemField(self):
        """Test EntItemField"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
