# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.api.maintenance_api import MaintenanceApi


class TestMaintenanceApi(unittest.TestCase):
    """MaintenanceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MaintenanceApi()

    def tearDown(self) -> None:
        pass

    def test_v1_maintenance_get(self) -> None:
        """Test case for v1_maintenance_get

        Query All Maintenance
        """
        pass

    def test_v1_maintenance_id_delete(self) -> None:
        """Test case for v1_maintenance_id_delete

        Delete Maintenance Entry
        """
        pass

    def test_v1_maintenance_id_put(self) -> None:
        """Test case for v1_maintenance_id_put

        Update Maintenance Entry
        """
        pass


if __name__ == '__main__':
    unittest.main()
