# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_notifier import EntNotifier

class TestEntNotifier(unittest.TestCase):
    """EntNotifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntNotifier:
        """Test EntNotifier
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntNotifier`
        """
        model = EntNotifier()
        if include_optional:
            return EntNotifier(
                created_at = '',
                edges = homebox_client.models.ent/notifier_edges.ent.NotifierEdges(
                    group = homebox_client.models.group.group(), 
                    user = homebox_client.models.user.user(), ),
                group_id = '',
                id = '',
                is_active = True,
                name = '',
                updated_at = '',
                user_id = ''
            )
        else:
            return EntNotifier(
        )
        """

    def testEntNotifier(self):
        """Test EntNotifier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
