# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_item_create import RepoItemCreate

class TestRepoItemCreate(unittest.TestCase):
    """RepoItemCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoItemCreate:
        """Test RepoItemCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoItemCreate`
        """
        model = RepoItemCreate()
        if include_optional:
            return RepoItemCreate(
                description = '',
                label_ids = [
                    ''
                    ],
                location_id = '',
                name = '0',
                parent_id = '',
                quantity = 56
            )
        else:
            return RepoItemCreate(
                name = '0',
        )
        """

    def testRepoItemCreate(self):
        """Test RepoItemCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
