# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_location_out import RepoLocationOut

class TestRepoLocationOut(unittest.TestCase):
    """RepoLocationOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoLocationOut:
        """Test RepoLocationOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoLocationOut`
        """
        model = RepoLocationOut()
        if include_optional:
            return RepoLocationOut(
                children = [
                    homebox_client.models.repo/location_summary.repo.LocationSummary(
                        created_at = '', 
                        description = '', 
                        id = '', 
                        name = '', 
                        updated_at = '', )
                    ],
                created_at = '',
                description = '',
                id = '',
                name = '',
                parent = homebox_client.models.repo/location_summary.repo.LocationSummary(
                    created_at = '', 
                    description = '', 
                    id = '', 
                    name = '', 
                    updated_at = '', ),
                total_price = 1.337,
                updated_at = ''
            )
        else:
            return RepoLocationOut(
        )
        """

    def testRepoLocationOut(self):
        """Test RepoLocationOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
