# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.api.items_attachments_api import ItemsAttachmentsApi


class TestItemsAttachmentsApi(unittest.TestCase):
    """ItemsAttachmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ItemsAttachmentsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_items_id_attachments_attachment_id_delete(self) -> None:
        """Test case for v1_items_id_attachments_attachment_id_delete

        Delete Item Attachment
        """
        pass

    def test_v1_items_id_attachments_attachment_id_get(self) -> None:
        """Test case for v1_items_id_attachments_attachment_id_get

        Get Item Attachment
        """
        pass

    def test_v1_items_id_attachments_attachment_id_put(self) -> None:
        """Test case for v1_items_id_attachments_attachment_id_put

        Update Item Attachment
        """
        pass

    def test_v1_items_id_attachments_post(self) -> None:
        """Test case for v1_items_id_attachments_post

        Create Item Attachment
        """
        pass


if __name__ == '__main__':
    unittest.main()
