# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_item import EntItem

class TestEntItem(unittest.TestCase):
    """EntItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntItem:
        """Test EntItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntItem`
        """
        model = EntItem()
        if include_optional:
            return EntItem(
                archived = True,
                asset_id = 56,
                created_at = '',
                description = '',
                edges = homebox_client.models.ent/item_edges.ent.ItemEdges(
                    attachments = [
                        homebox_client.models.ent/attachment.ent.Attachment(
                            created_at = '', 
                            edges = homebox_client.models.edges.edges(), 
                            id = '', 
                            mime_type = '', 
                            path = '', 
                            primary = True, 
                            title = '', 
                            type = homebox_client.models.type.type(), 
                            updated_at = '', )
                        ], 
                    children = [
                        homebox_client.models.ent/item.ent.Item(
                            archived = True, 
                            asset_id = 56, 
                            created_at = '', 
                            description = '', 
                            edges = homebox_client.models.edges.edges(), 
                            id = '', 
                            import_ref = '', 
                            insured = True, 
                            lifetime_warranty = True, 
                            manufacturer = '', 
                            model_number = '', 
                            name = '', 
                            notes = '', 
                            purchase_from = '', 
                            purchase_price = 1.337, 
                            purchase_time = '', 
                            quantity = 56, 
                            serial_number = '', 
                            sold_notes = '', 
                            sold_price = 1.337, 
                            sold_time = '', 
                            sold_to = '', 
                            sync_child_items_locations = True, 
                            updated_at = '', 
                            warranty_details = '', 
                            warranty_expires = '', )
                        ], 
                    fields = [
                        homebox_client.models.ent/item_field.ent.ItemField(
                            boolean_value = True, 
                            created_at = '', 
                            description = '', 
                            edges = homebox_client.models.edges.edges(), 
                            id = '', 
                            name = '', 
                            number_value = 56, 
                            text_value = '', 
                            time_value = '', 
                            type = homebox_client.models.type.type(), 
                            updated_at = '', )
                        ], 
                    group = homebox_client.models.group.group(), 
                    label = [
                        homebox_client.models.ent/label.ent.Label(
                            color = '', 
                            created_at = '', 
                            description = '', 
                            edges = homebox_client.models.edges.edges(), 
                            id = '', 
                            name = '', 
                            updated_at = '', )
                        ], 
                    location = homebox_client.models.location.location(), 
                    maintenance_entries = [
                        homebox_client.models.ent/maintenance_entry.ent.MaintenanceEntry(
                            cost = 1.337, 
                            created_at = '', 
                            date = '', 
                            description = '', 
                            edges = homebox_client.models.edges.edges(), 
                            id = '', 
                            item_id = '', 
                            name = '', 
                            scheduled_date = '', 
                            updated_at = '', )
                        ], 
                    parent = homebox_client.models.parent.parent(), ),
                id = '',
                import_ref = '',
                insured = True,
                lifetime_warranty = True,
                manufacturer = '',
                model_number = '',
                name = '',
                notes = '',
                purchase_from = '',
                purchase_price = 1.337,
                purchase_time = '',
                quantity = 56,
                serial_number = '',
                sold_notes = '',
                sold_price = 1.337,
                sold_time = '',
                sold_to = '',
                sync_child_items_locations = True,
                updated_at = '',
                warranty_details = '',
                warranty_expires = ''
            )
        else:
            return EntItem(
        )
        """

    def testEntItem(self):
        """Test EntItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
