# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.v1_users_self_get200_response import V1UsersSelfGet200Response

class TestV1UsersSelfGet200Response(unittest.TestCase):
    """V1UsersSelfGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1UsersSelfGet200Response:
        """Test V1UsersSelfGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1UsersSelfGet200Response`
        """
        model = V1UsersSelfGet200Response()
        if include_optional:
            return V1UsersSelfGet200Response(
                item = homebox_client.models.repo/user_out.repo.UserOut(
                    email = '', 
                    group_id = '', 
                    group_name = '', 
                    id = '', 
                    is_owner = True, 
                    is_superuser = True, 
                    name = '', )
            )
        else:
            return V1UsersSelfGet200Response(
        )
        """

    def testV1UsersSelfGet200Response(self):
        """Test V1UsersSelfGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
