# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_location_create import RepoLocationCreate

class TestRepoLocationCreate(unittest.TestCase):
    """RepoLocationCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoLocationCreate:
        """Test RepoLocationCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoLocationCreate`
        """
        model = RepoLocationCreate()
        if include_optional:
            return RepoLocationCreate(
                description = '',
                name = '',
                parent_id = ''
            )
        else:
            return RepoLocationCreate(
        )
        """

    def testRepoLocationCreate(self):
        """Test RepoLocationCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
