# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_group import EntGroup

class TestEntGroup(unittest.TestCase):
    """EntGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntGroup:
        """Test EntGroup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntGroup`
        """
        model = EntGroup()
        if include_optional:
            return EntGroup(
                created_at = '',
                currency = '',
                edges = homebox_client.models.ent/group_edges.ent.GroupEdges(
                    invitation_tokens = [
                        homebox_client.models.ent/group_invitation_token.ent.GroupInvitationToken(
                            created_at = '', 
                            edges = homebox_client.models.edges.edges(), 
                            expires_at = '', 
                            id = '', 
                            token = [
                                56
                                ], 
                            updated_at = '', 
                            uses = 56, )
                        ], 
                    items = [
                        homebox_client.models.ent/item.ent.Item(
                            archived = True, 
                            asset_id = 56, 
                            created_at = '', 
                            description = '', 
                            edges = homebox_client.models.edges.edges(), 
                            id = '', 
                            import_ref = '', 
                            insured = True, 
                            lifetime_warranty = True, 
                            manufacturer = '', 
                            model_number = '', 
                            name = '', 
                            notes = '', 
                            purchase_from = '', 
                            purchase_price = 1.337, 
                            purchase_time = '', 
                            quantity = 56, 
                            serial_number = '', 
                            sold_notes = '', 
                            sold_price = 1.337, 
                            sold_time = '', 
                            sold_to = '', 
                            sync_child_items_locations = True, 
                            updated_at = '', 
                            warranty_details = '', 
                            warranty_expires = '', )
                        ], 
                    labels = [
                        homebox_client.models.ent/label.ent.Label(
                            color = '', 
                            created_at = '', 
                            description = '', 
                            edges = homebox_client.models.edges.edges(), 
                            id = '', 
                            name = '', 
                            updated_at = '', )
                        ], 
                    locations = [
                        homebox_client.models.ent/location.ent.Location(
                            created_at = '', 
                            description = '', 
                            edges = homebox_client.models.edges.edges(), 
                            id = '', 
                            name = '', 
                            updated_at = '', )
                        ], 
                    notifiers = [
                        homebox_client.models.ent/notifier.ent.Notifier(
                            created_at = '', 
                            edges = homebox_client.models.edges.edges(), 
                            group_id = '', 
                            id = '', 
                            is_active = True, 
                            name = '', 
                            updated_at = '', 
                            user_id = '', )
                        ], 
                    users = [
                        homebox_client.models.ent/user.ent.User(
                            activated_on = '', 
                            created_at = '', 
                            edges = homebox_client.models.edges.edges(), 
                            email = '', 
                            id = '', 
                            is_superuser = True, 
                            name = '', 
                            role = homebox_client.models.role.role(), 
                            superuser = True, 
                            updated_at = '', )
                        ], ),
                id = '',
                name = '',
                updated_at = ''
            )
        else:
            return EntGroup(
        )
        """

    def testEntGroup(self):
        """Test EntGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
