# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_auth_tokens import EntAuthTokens

class TestEntAuthTokens(unittest.TestCase):
    """EntAuthTokens unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntAuthTokens:
        """Test EntAuthTokens
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntAuthTokens`
        """
        model = EntAuthTokens()
        if include_optional:
            return EntAuthTokens(
                created_at = '',
                edges = homebox_client.models.ent/auth_tokens_edges.ent.AuthTokensEdges(
                    roles = homebox_client.models.roles.roles(), 
                    user = homebox_client.models.user.user(), ),
                expires_at = '',
                id = '',
                token = [
                    56
                    ],
                updated_at = ''
            )
        else:
            return EntAuthTokens(
        )
        """

    def testEntAuthTokens(self):
        """Test EntAuthTokens"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
