# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_group_statistics import RepoGroupStatistics

class TestRepoGroupStatistics(unittest.TestCase):
    """RepoGroupStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoGroupStatistics:
        """Test RepoGroupStatistics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoGroupStatistics`
        """
        model = RepoGroupStatistics()
        if include_optional:
            return RepoGroupStatistics(
                total_item_price = 1.337,
                total_items = 56,
                total_labels = 56,
                total_locations = 56,
                total_users = 56,
                total_with_warranty = 56
            )
        else:
            return RepoGroupStatistics(
        )
        """

    def testRepoGroupStatistics(self):
        """Test RepoGroupStatistics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
