# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_item_update import RepoItemUpdate

class TestRepoItemUpdate(unittest.TestCase):
    """RepoItemUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoItemUpdate:
        """Test RepoItemUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoItemUpdate`
        """
        model = RepoItemUpdate()
        if include_optional:
            return RepoItemUpdate(
                archived = True,
                asset_id = '',
                description = '',
                fields = [
                    homebox_client.models.repo/item_field.repo.ItemField(
                        boolean_value = True, 
                        id = '', 
                        name = '', 
                        number_value = 56, 
                        text_value = '', 
                        type = '', )
                    ],
                id = '',
                insured = True,
                label_ids = [
                    ''
                    ],
                lifetime_warranty = True,
                location_id = '',
                manufacturer = '',
                model_number = '',
                name = '0',
                notes = '',
                parent_id = '',
                purchase_from = '',
                purchase_price = 1.337,
                purchase_time = '',
                quantity = 56,
                serial_number = '',
                sold_notes = '',
                sold_price = 1.337,
                sold_time = '',
                sold_to = '',
                sync_child_items_locations = True,
                warranty_details = '',
                warranty_expires = ''
            )
        else:
            return RepoItemUpdate(
                name = '0',
        )
        """

    def testRepoItemUpdate(self):
        """Test RepoItemUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
