# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_totals_by_organizer import RepoTotalsByOrganizer

class TestRepoTotalsByOrganizer(unittest.TestCase):
    """RepoTotalsByOrganizer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoTotalsByOrganizer:
        """Test RepoTotalsByOrganizer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoTotalsByOrganizer`
        """
        model = RepoTotalsByOrganizer()
        if include_optional:
            return RepoTotalsByOrganizer(
                id = '',
                name = '',
                total = 1.337
            )
        else:
            return RepoTotalsByOrganizer(
        )
        """

    def testRepoTotalsByOrganizer(self):
        """Test RepoTotalsByOrganizer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
