# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.v1_wrapped import V1Wrapped

class TestV1Wrapped(unittest.TestCase):
    """V1Wrapped unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1Wrapped:
        """Test V1Wrapped
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1Wrapped`
        """
        model = V1Wrapped()
        if include_optional:
            return V1Wrapped(
                item = None
            )
        else:
            return V1Wrapped(
        )
        """

    def testV1Wrapped(self):
        """Test V1Wrapped"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
