# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_item_patch import RepoItemPatch

class TestRepoItemPatch(unittest.TestCase):
    """RepoItemPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoItemPatch:
        """Test RepoItemPatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoItemPatch`
        """
        model = RepoItemPatch()
        if include_optional:
            return RepoItemPatch(
                id = '',
                quantity = 56
            )
        else:
            return RepoItemPatch(
        )
        """

    def testRepoItemPatch(self):
        """Test RepoItemPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
