# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.api.item_maintenance_api import ItemMaintenanceApi


class TestItemMaintenanceApi(unittest.TestCase):
    """ItemMaintenanceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ItemMaintenanceApi()

    def tearDown(self) -> None:
        pass

    def test_v1_items_id_maintenance_get(self) -> None:
        """Test case for v1_items_id_maintenance_get

        Get Maintenance Log
        """
        pass

    def test_v1_items_id_maintenance_post(self) -> None:
        """Test case for v1_items_id_maintenance_post

        Create Maintenance Entry
        """
        pass


if __name__ == '__main__':
    unittest.main()
