# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_item_attachment import RepoItemAttachment

class TestRepoItemAttachment(unittest.TestCase):
    """RepoItemAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoItemAttachment:
        """Test RepoItemAttachment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoItemAttachment`
        """
        model = RepoItemAttachment()
        if include_optional:
            return RepoItemAttachment(
                created_at = '',
                id = '',
                mime_type = '',
                path = '',
                primary = True,
                thumbnail = homebox_client.models.ent/attachment.ent.Attachment(
                    created_at = '', 
                    edges = homebox_client.models.edges.edges(), 
                    id = '', 
                    mime_type = '', 
                    path = '', 
                    primary = True, 
                    title = '', 
                    type = homebox_client.models.type.type(), 
                    updated_at = '', ),
                title = '',
                type = '',
                updated_at = ''
            )
        else:
            return RepoItemAttachment(
        )
        """

    def testRepoItemAttachment(self):
        """Test RepoItemAttachment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
