# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.api.actions_api import ActionsApi


class TestActionsApi(unittest.TestCase):
    """ActionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActionsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_actions_create_missing_thumbnails_post(self) -> None:
        """Test case for v1_actions_create_missing_thumbnails_post

        Create Missing Thumbnails
        """
        pass

    def test_v1_actions_ensure_asset_ids_post(self) -> None:
        """Test case for v1_actions_ensure_asset_ids_post

        Ensure Asset IDs
        """
        pass

    def test_v1_actions_ensure_import_refs_post(self) -> None:
        """Test case for v1_actions_ensure_import_refs_post

        Ensures Import Refs
        """
        pass

    def test_v1_actions_set_primary_photos_post(self) -> None:
        """Test case for v1_actions_set_primary_photos_post

        Set Primary Photos
        """
        pass

    def test_v1_actions_zero_item_time_fields_post(self) -> None:
        """Test case for v1_actions_zero_item_time_fields_post

        Zero Out Time Fields
        """
        pass


if __name__ == '__main__':
    unittest.main()
