# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.api.items_api import ItemsApi


class TestItemsApi(unittest.TestCase):
    """ItemsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ItemsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_assets_id_get(self) -> None:
        """Test case for v1_assets_id_get

        Get Item by Asset ID
        """
        pass

    def test_v1_items_export_get(self) -> None:
        """Test case for v1_items_export_get

        Export Items
        """
        pass

    def test_v1_items_fields_get(self) -> None:
        """Test case for v1_items_fields_get

        Get All Custom Field Names
        """
        pass

    def test_v1_items_fields_values_get(self) -> None:
        """Test case for v1_items_fields_values_get

        Get All Custom Field Values
        """
        pass

    def test_v1_items_get(self) -> None:
        """Test case for v1_items_get

        Query All Items
        """
        pass

    def test_v1_items_id_delete(self) -> None:
        """Test case for v1_items_id_delete

        Delete Item
        """
        pass

    def test_v1_items_id_duplicate_post(self) -> None:
        """Test case for v1_items_id_duplicate_post

        Duplicate Item
        """
        pass

    def test_v1_items_id_get(self) -> None:
        """Test case for v1_items_id_get

        Get Item
        """
        pass

    def test_v1_items_id_patch(self) -> None:
        """Test case for v1_items_id_patch

        Update Item
        """
        pass

    def test_v1_items_id_path_get(self) -> None:
        """Test case for v1_items_id_path_get

        Get the full path of an item
        """
        pass

    def test_v1_items_id_put(self) -> None:
        """Test case for v1_items_id_put

        Update Item
        """
        pass

    def test_v1_items_import_post(self) -> None:
        """Test case for v1_items_import_post

        Import Items
        """
        pass

    def test_v1_items_post(self) -> None:
        """Test case for v1_items_post

        Create Item
        """
        pass

    def test_v1_labelmaker_assets_id_get(self) -> None:
        """Test case for v1_labelmaker_assets_id_get

        Get Asset label
        """
        pass

    def test_v1_labelmaker_item_id_get(self) -> None:
        """Test case for v1_labelmaker_item_id_get

        Get Item label
        """
        pass

    def test_v1_products_search_from_barcode_get(self) -> None:
        """Test case for v1_products_search_from_barcode_get

        Search EAN from Barcode
        """
        pass

    def test_v1_qrcode_get(self) -> None:
        """Test case for v1_qrcode_get

        Create QR Code
        """
        pass


if __name__ == '__main__':
    unittest.main()
