# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_attachment_edges import EntAttachmentEdges

class TestEntAttachmentEdges(unittest.TestCase):
    """EntAttachmentEdges unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntAttachmentEdges:
        """Test EntAttachmentEdges
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntAttachmentEdges`
        """
        model = EntAttachmentEdges()
        if include_optional:
            return EntAttachmentEdges(
                item = homebox_client.models.ent/item.ent.Item(
                    archived = True, 
                    asset_id = 56, 
                    created_at = '', 
                    description = '', 
                    edges = homebox_client.models.edges.edges(), 
                    id = '', 
                    import_ref = '', 
                    insured = True, 
                    lifetime_warranty = True, 
                    manufacturer = '', 
                    model_number = '', 
                    name = '', 
                    notes = '', 
                    purchase_from = '', 
                    purchase_price = 1.337, 
                    purchase_time = '', 
                    quantity = 56, 
                    serial_number = '', 
                    sold_notes = '', 
                    sold_price = 1.337, 
                    sold_time = '', 
                    sold_to = '', 
                    sync_child_items_locations = True, 
                    updated_at = '', 
                    warranty_details = '', 
                    warranty_expires = '', ),
                thumbnail = homebox_client.models.ent/attachment.ent.Attachment(
                    created_at = '', 
                    edges = homebox_client.models.edges.edges(), 
                    id = '', 
                    mime_type = '', 
                    path = '', 
                    primary = True, 
                    title = '', 
                    type = homebox_client.models.type.type(), 
                    updated_at = '', )
            )
        else:
            return EntAttachmentEdges(
        )
        """

    def testEntAttachmentEdges(self):
        """Test EntAttachmentEdges"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
