# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_tree_item import RepoTreeItem

class TestRepoTreeItem(unittest.TestCase):
    """RepoTreeItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoTreeItem:
        """Test RepoTreeItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoTreeItem`
        """
        model = RepoTreeItem()
        if include_optional:
            return RepoTreeItem(
                children = [
                    homebox_client.models.repo/tree_item.repo.TreeItem(
                        children = [
                            homebox_client.models.repo/tree_item.repo.TreeItem(
                                id = '', 
                                name = '', 
                                type = '', )
                            ], 
                        id = '', 
                        name = '', 
                        type = '', )
                    ],
                id = '',
                name = '',
                type = ''
            )
        else:
            return RepoTreeItem(
        )
        """

    def testRepoTreeItem(self):
        """Test RepoTreeItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
