# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_item_path import RepoItemPath

class TestRepoItemPath(unittest.TestCase):
    """RepoItemPath unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoItemPath:
        """Test RepoItemPath
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoItemPath`
        """
        model = RepoItemPath()
        if include_optional:
            return RepoItemPath(
                id = '',
                name = '',
                type = 'location'
            )
        else:
            return RepoItemPath(
        )
        """

    def testRepoItemPath(self):
        """Test RepoItemPath"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
