# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.itemfield_type import ItemfieldType

class TestItemfieldType(unittest.TestCase):
    """ItemfieldType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemfieldType(self):
        """Test ItemfieldType"""
        # inst = ItemfieldType()

if __name__ == '__main__':
    unittest.main()
