# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_group_invitation_token import EntGroupInvitationToken

class TestEntGroupInvitationToken(unittest.TestCase):
    """EntGroupInvitationToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntGroupInvitationToken:
        """Test EntGroupInvitationToken
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntGroupInvitationToken`
        """
        model = EntGroupInvitationToken()
        if include_optional:
            return EntGroupInvitationToken(
                created_at = '',
                edges = homebox_client.models.ent/group_invitation_token_edges.ent.GroupInvitationTokenEdges(
                    group = homebox_client.models.group.group(), ),
                expires_at = '',
                id = '',
                token = [
                    56
                    ],
                updated_at = '',
                uses = 56
            )
        else:
            return EntGroupInvitationToken(
        )
        """

    def testEntGroupInvitationToken(self):
        """Test EntGroupInvitationToken"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
