# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.api.base_api import BaseApi


class TestBaseApi(unittest.TestCase):
    """BaseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BaseApi()

    def tearDown(self) -> None:
        pass

    def test_v1_currency_get(self) -> None:
        """Test case for v1_currency_get

        Currency
        """
        pass

    def test_v1_status_get(self) -> None:
        """Test case for v1_status_get

        Application Info
        """
        pass


if __name__ == '__main__':
    unittest.main()
