# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_v1_users_change_password_put(self) -> None:
        """Test case for v1_users_change_password_put

        Change Password
        """
        pass

    def test_v1_users_register_post(self) -> None:
        """Test case for v1_users_register_post

        Register New User
        """
        pass

    def test_v1_users_self_delete(self) -> None:
        """Test case for v1_users_self_delete

        Delete Account
        """
        pass

    def test_v1_users_self_get(self) -> None:
        """Test case for v1_users_self_get

        Get User Self
        """
        pass

    def test_v1_users_self_put(self) -> None:
        """Test case for v1_users_self_put

        Update Account
        """
        pass


if __name__ == '__main__':
    unittest.main()
