# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_user import EntUser

class TestEntUser(unittest.TestCase):
    """EntUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntUser:
        """Test EntUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntUser`
        """
        model = EntUser()
        if include_optional:
            return EntUser(
                activated_on = '',
                created_at = '',
                edges = homebox_client.models.ent/user_edges.ent.UserEdges(
                    auth_tokens = [
                        homebox_client.models.ent/auth_tokens.ent.AuthTokens(
                            created_at = '', 
                            edges = homebox_client.models.edges.edges(), 
                            expires_at = '', 
                            id = '', 
                            token = [
                                56
                                ], 
                            updated_at = '', )
                        ], 
                    group = homebox_client.models.group.group(), 
                    notifiers = [
                        homebox_client.models.ent/notifier.ent.Notifier(
                            created_at = '', 
                            edges = homebox_client.models.edges.edges(), 
                            group_id = '', 
                            id = '', 
                            is_active = True, 
                            name = '', 
                            updated_at = '', 
                            user_id = '', )
                        ], ),
                email = '',
                id = '',
                is_superuser = True,
                name = '',
                role = 'user',
                superuser = True,
                updated_at = ''
            )
        else:
            return EntUser(
        )
        """

    def testEntUser(self):
        """Test EntUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
