# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.api.group_api import GroupApi


class TestGroupApi(unittest.TestCase):
    """GroupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupApi()

    def tearDown(self) -> None:
        pass

    def test_v1_groups_get(self) -> None:
        """Test case for v1_groups_get

        Get Group
        """
        pass

    def test_v1_groups_invitations_post(self) -> None:
        """Test case for v1_groups_invitations_post

        Create Group Invitation
        """
        pass

    def test_v1_groups_put(self) -> None:
        """Test case for v1_groups_put

        Update Group
        """
        pass


if __name__ == '__main__':
    unittest.main()
