# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_auth_tokens_edges import EntAuthTokensEdges

class TestEntAuthTokensEdges(unittest.TestCase):
    """EntAuthTokensEdges unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntAuthTokensEdges:
        """Test EntAuthTokensEdges
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntAuthTokensEdges`
        """
        model = EntAuthTokensEdges()
        if include_optional:
            return EntAuthTokensEdges(
                roles = homebox_client.models.ent/auth_roles.ent.AuthRoles(
                    edges = homebox_client.models.edges.edges(), 
                    id = 56, 
                    role = homebox_client.models.role.role(), ),
                user = homebox_client.models.ent/user.ent.User(
                    activated_on = '', 
                    created_at = '', 
                    edges = homebox_client.models.edges.edges(), 
                    email = '', 
                    id = '', 
                    is_superuser = True, 
                    name = '', 
                    role = homebox_client.models.role.role(), 
                    superuser = True, 
                    updated_at = '', )
            )
        else:
            return EntAuthTokensEdges(
        )
        """

    def testEntAuthTokensEdges(self):
        """Test EntAuthTokensEdges"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
