# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_maintenance_filter_status import RepoMaintenanceFilterStatus

class TestRepoMaintenanceFilterStatus(unittest.TestCase):
    """RepoMaintenanceFilterStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepoMaintenanceFilterStatus(self):
        """Test RepoMaintenanceFilterStatus"""
        # inst = RepoMaintenanceFilterStatus()

if __name__ == '__main__':
    unittest.main()
