# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_value_over_time import RepoValueOverTime

class TestRepoValueOverTime(unittest.TestCase):
    """RepoValueOverTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoValueOverTime:
        """Test RepoValueOverTime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoValueOverTime`
        """
        model = RepoValueOverTime()
        if include_optional:
            return RepoValueOverTime(
                end = '',
                entries = [
                    homebox_client.models.repo/value_over_time_entry.repo.ValueOverTimeEntry(
                        date = '', 
                        name = '', 
                        value = 1.337, )
                    ],
                start = '',
                value_at_end = 1.337,
                value_at_start = 1.337
            )
        else:
            return RepoValueOverTime(
        )
        """

    def testRepoValueOverTime(self):
        """Test RepoValueOverTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
