# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.v1_item_attachment_token import V1ItemAttachmentToken

class TestV1ItemAttachmentToken(unittest.TestCase):
    """V1ItemAttachmentToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ItemAttachmentToken:
        """Test V1ItemAttachmentToken
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ItemAttachmentToken`
        """
        model = V1ItemAttachmentToken()
        if include_optional:
            return V1ItemAttachmentToken(
                token = ''
            )
        else:
            return V1ItemAttachmentToken(
        )
        """

    def testV1ItemAttachmentToken(self):
        """Test V1ItemAttachmentToken"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
