# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_maintenance_entry import EntMaintenanceEntry

class TestEntMaintenanceEntry(unittest.TestCase):
    """EntMaintenanceEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntMaintenanceEntry:
        """Test EntMaintenanceEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntMaintenanceEntry`
        """
        model = EntMaintenanceEntry()
        if include_optional:
            return EntMaintenanceEntry(
                cost = 1.337,
                created_at = '',
                var_date = '',
                description = '',
                edges = homebox_client.models.ent/maintenance_entry_edges.ent.MaintenanceEntryEdges(
                    item = homebox_client.models.item.item(), ),
                id = '',
                item_id = '',
                name = '',
                scheduled_date = '',
                updated_at = ''
            )
        else:
            return EntMaintenanceEntry(
        )
        """

    def testEntMaintenanceEntry(self):
        """Test EntMaintenanceEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
