# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_item_summary import RepoItemSummary

class TestRepoItemSummary(unittest.TestCase):
    """RepoItemSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoItemSummary:
        """Test RepoItemSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoItemSummary`
        """
        model = RepoItemSummary()
        if include_optional:
            return RepoItemSummary(
                archived = True,
                asset_id = '0',
                created_at = '',
                description = '',
                id = '',
                image_id = '',
                insured = True,
                labels = [
                    homebox_client.models.repo/label_summary.repo.LabelSummary(
                        color = '', 
                        created_at = '', 
                        description = '', 
                        id = '', 
                        name = '', 
                        updated_at = '', )
                    ],
                location = homebox_client.models.repo/location_summary.repo.LocationSummary(
                    created_at = '', 
                    description = '', 
                    id = '', 
                    name = '', 
                    updated_at = '', ),
                name = '',
                purchase_price = 1.337,
                quantity = 56,
                sold_time = '',
                thumbnail_id = '',
                updated_at = ''
            )
        else:
            return RepoItemSummary(
        )
        """

    def testRepoItemSummary(self):
        """Test RepoItemSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
