# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.services_latest import ServicesLatest

class TestServicesLatest(unittest.TestCase):
    """ServicesLatest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServicesLatest:
        """Test ServicesLatest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServicesLatest`
        """
        model = ServicesLatest()
        if include_optional:
            return ServicesLatest(
                var_date = '',
                version = ''
            )
        else:
            return ServicesLatest(
        )
        """

    def testServicesLatest(self):
        """Test ServicesLatest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
