# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_maintenance_entry import RepoMaintenanceEntry

class TestRepoMaintenanceEntry(unittest.TestCase):
    """RepoMaintenanceEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoMaintenanceEntry:
        """Test RepoMaintenanceEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoMaintenanceEntry`
        """
        model = RepoMaintenanceEntry()
        if include_optional:
            return RepoMaintenanceEntry(
                completed_date = '',
                cost = '0',
                description = '',
                id = '',
                name = '',
                scheduled_date = ''
            )
        else:
            return RepoMaintenanceEntry(
        )
        """

    def testRepoMaintenanceEntry(self):
        """Test RepoMaintenanceEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
