# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.v1_login_form import V1LoginForm

class TestV1LoginForm(unittest.TestCase):
    """V1LoginForm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1LoginForm:
        """Test V1LoginForm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1LoginForm`
        """
        model = V1LoginForm()
        if include_optional:
            return V1LoginForm(
                password = 'admin',
                stay_logged_in = True,
                username = 'admin@admin.com'
            )
        else:
            return V1LoginForm(
        )
        """

    def testV1LoginForm(self):
        """Test V1LoginForm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
