# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_v1_users_login_post(self) -> None:
        """Test case for v1_users_login_post

        User Login
        """
        pass

    def test_v1_users_logout_post(self) -> None:
        """Test case for v1_users_logout_post

        User Logout
        """
        pass

    def test_v1_users_refresh_get(self) -> None:
        """Test case for v1_users_refresh_get

        User Token Refresh
        """
        pass


if __name__ == '__main__':
    unittest.main()
