# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_user_edges import EntUserEdges

class TestEntUserEdges(unittest.TestCase):
    """EntUserEdges unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntUserEdges:
        """Test EntUserEdges
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntUserEdges`
        """
        model = EntUserEdges()
        if include_optional:
            return EntUserEdges(
                auth_tokens = [
                    homebox_client.models.ent/auth_tokens.ent.AuthTokens(
                        created_at = '', 
                        edges = homebox_client.models.edges.edges(), 
                        expires_at = '', 
                        id = '', 
                        token = [
                            56
                            ], 
                        updated_at = '', )
                    ],
                group = homebox_client.models.ent/group.ent.Group(
                    created_at = '', 
                    currency = '', 
                    edges = homebox_client.models.edges.edges(), 
                    id = '', 
                    name = '', 
                    updated_at = '', ),
                notifiers = [
                    homebox_client.models.ent/notifier.ent.Notifier(
                        created_at = '', 
                        edges = homebox_client.models.edges.edges(), 
                        group_id = '', 
                        id = '', 
                        is_active = True, 
                        name = '', 
                        updated_at = '', 
                        user_id = '', )
                    ]
            )
        else:
            return EntUserEdges(
        )
        """

    def testEntUserEdges(self):
        """Test EntUserEdges"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
