# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_notifier_out import RepoNotifierOut

class TestRepoNotifierOut(unittest.TestCase):
    """RepoNotifierOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoNotifierOut:
        """Test RepoNotifierOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoNotifierOut`
        """
        model = RepoNotifierOut()
        if include_optional:
            return RepoNotifierOut(
                created_at = '',
                group_id = '',
                id = '',
                is_active = True,
                name = '',
                updated_at = '',
                url = '',
                user_id = ''
            )
        else:
            return RepoNotifierOut(
        )
        """

    def testRepoNotifierOut(self):
        """Test RepoNotifierOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
