# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.attachment_type import AttachmentType

class TestAttachmentType(unittest.TestCase):
    """AttachmentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachmentType(self):
        """Test AttachmentType"""
        # inst = AttachmentType()

if __name__ == '__main__':
    unittest.main()
