# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.api.locations_api import LocationsApi


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LocationsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_labelmaker_location_id_get(self) -> None:
        """Test case for v1_labelmaker_location_id_get

        Get Location label
        """
        pass

    def test_v1_locations_get(self) -> None:
        """Test case for v1_locations_get

        Get All Locations
        """
        pass

    def test_v1_locations_id_delete(self) -> None:
        """Test case for v1_locations_id_delete

        Delete Location
        """
        pass

    def test_v1_locations_id_get(self) -> None:
        """Test case for v1_locations_id_get

        Get Location
        """
        pass

    def test_v1_locations_id_put(self) -> None:
        """Test case for v1_locations_id_put

        Update Location
        """
        pass

    def test_v1_locations_post(self) -> None:
        """Test case for v1_locations_post

        Create Location
        """
        pass

    def test_v1_locations_tree_get(self) -> None:
        """Test case for v1_locations_tree_get

        Get Locations Tree
        """
        pass


if __name__ == '__main__':
    unittest.main()
