# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.ent_group_invitation_token_edges import EntGroupInvitationTokenEdges

class TestEntGroupInvitationTokenEdges(unittest.TestCase):
    """EntGroupInvitationTokenEdges unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntGroupInvitationTokenEdges:
        """Test EntGroupInvitationTokenEdges
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntGroupInvitationTokenEdges`
        """
        model = EntGroupInvitationTokenEdges()
        if include_optional:
            return EntGroupInvitationTokenEdges(
                group = homebox_client.models.ent/group.ent.Group(
                    created_at = '', 
                    currency = '', 
                    edges = homebox_client.models.edges.edges(), 
                    id = '', 
                    name = '', 
                    updated_at = '', )
            )
        else:
            return EntGroupInvitationTokenEdges(
        )
        """

    def testEntGroupInvitationTokenEdges(self):
        """Test EntGroupInvitationTokenEdges"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
