# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_item_out import RepoItemOut

class TestRepoItemOut(unittest.TestCase):
    """RepoItemOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoItemOut:
        """Test RepoItemOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoItemOut`
        """
        model = RepoItemOut()
        if include_optional:
            return RepoItemOut(
                archived = True,
                asset_id = '0',
                attachments = [
                    homebox_client.models.repo/item_attachment.repo.ItemAttachment(
                        created_at = '', 
                        id = '', 
                        mime_type = '', 
                        path = '', 
                        primary = True, 
                        thumbnail = homebox_client.models.ent/attachment.ent.Attachment(
                            created_at = '', 
                            edges = homebox_client.models.edges.edges(), 
                            id = '', 
                            mime_type = '', 
                            path = '', 
                            primary = True, 
                            title = '', 
                            type = homebox_client.models.type.type(), 
                            updated_at = '', ), 
                        title = '', 
                        type = '', 
                        updated_at = '', )
                    ],
                created_at = '',
                description = '',
                fields = [
                    homebox_client.models.repo/item_field.repo.ItemField(
                        boolean_value = True, 
                        id = '', 
                        name = '', 
                        number_value = 56, 
                        text_value = '', 
                        type = '', )
                    ],
                id = '',
                image_id = '',
                insured = True,
                labels = [
                    homebox_client.models.repo/label_summary.repo.LabelSummary(
                        color = '', 
                        created_at = '', 
                        description = '', 
                        id = '', 
                        name = '', 
                        updated_at = '', )
                    ],
                lifetime_warranty = True,
                location = homebox_client.models.repo/location_summary.repo.LocationSummary(
                    created_at = '', 
                    description = '', 
                    id = '', 
                    name = '', 
                    updated_at = '', ),
                manufacturer = '',
                model_number = '',
                name = '',
                notes = '',
                parent = homebox_client.models.repo/item_summary.repo.ItemSummary(
                    archived = True, 
                    asset_id = '0', 
                    created_at = '', 
                    description = '', 
                    id = '', 
                    image_id = '', 
                    insured = True, 
                    labels = [
                        homebox_client.models.repo/label_summary.repo.LabelSummary(
                            color = '', 
                            created_at = '', 
                            description = '', 
                            id = '', 
                            name = '', 
                            updated_at = '', )
                        ], 
                    location = homebox_client.models.location.location(), 
                    name = '', 
                    purchase_price = 1.337, 
                    quantity = 56, 
                    sold_time = '', 
                    thumbnail_id = '', 
                    updated_at = '', ),
                purchase_from = '',
                purchase_price = 1.337,
                purchase_time = '',
                quantity = 56,
                serial_number = '',
                sold_notes = '',
                sold_price = 1.337,
                sold_time = '',
                sold_to = '',
                sync_child_items_locations = True,
                thumbnail_id = '',
                updated_at = '',
                warranty_details = '',
                warranty_expires = ''
            )
        else:
            return RepoItemOut(
        )
        """

    def testRepoItemOut(self):
        """Test RepoItemOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
