# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from homebox_client.models.repo_notifier_create import RepoNotifierCreate

class TestRepoNotifierCreate(unittest.TestCase):
    """RepoNotifierCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepoNotifierCreate:
        """Test RepoNotifierCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepoNotifierCreate`
        """
        model = RepoNotifierCreate()
        if include_optional:
            return RepoNotifierCreate(
                is_active = True,
                name = '0',
                url = ''
            )
        else:
            return RepoNotifierCreate(
                name = '0',
                url = '',
        )
        """

    def testRepoNotifierCreate(self):
        """Test RepoNotifierCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
