# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by openapi-python-client (https://github.com/openapi-generators/openapi-python-client)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "homebox-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "attrs >= 22.2.0",
    "httpx >= 0.23.0, < 0.29.0",
]

setup(
    name=NAME,
    version=VERSION,
    description="Homebox API",
    author="Homebox Team",
    author_email="team@openapitools.org",
    url="https://github.com/pfa230/homebox_client",
    keywords=["OpenAPI", "openapi-python-client", "Homebox API"],
    license="MIT",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Track, Manage, and Organize your Things.
    """,  # noqa: E501
    package_data={"homebox_client": ["py.typed", "*.pyi"]},
)
