# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AttachmentType(str, Enum):
    """
    AttachmentType
    """

    """
    allowed enum values
    """
    DefaultType = 'attachment'
    TypePhoto = 'photo'
    TypeManual = 'manual'
    TypeWarranty = 'warranty'
    TypeAttachment = 'attachment'
    TypeReceipt = 'receipt'
    TypeThumbnail = 'thumbnail'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AttachmentType from a JSON string"""
        return cls(json.loads(json_str))


