# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class EntMaintenanceEntry(BaseModel):
    """
    EntMaintenanceEntry
    """ # noqa: E501
    cost: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Cost holds the value of the \"cost\" field.")
    created_at: Optional[StrictStr] = Field(default=None, description="CreatedAt holds the value of the \"created_at\" field.")
    var_date: Optional[StrictStr] = Field(default=None, description="Date holds the value of the \"date\" field.", alias="date")
    description: Optional[StrictStr] = Field(default=None, description="Description holds the value of the \"description\" field.")
    edges: Optional[EntMaintenanceEntryEdges] = Field(default=None, description="Edges holds the relations/edges for other nodes in the graph. The values are being populated by the MaintenanceEntryQuery when eager-loading is set.")
    id: Optional[StrictStr] = Field(default=None, description="ID of the ent.")
    item_id: Optional[StrictStr] = Field(default=None, description="ItemID holds the value of the \"item_id\" field.")
    name: Optional[StrictStr] = Field(default=None, description="Name holds the value of the \"name\" field.")
    scheduled_date: Optional[StrictStr] = Field(default=None, description="ScheduledDate holds the value of the \"scheduled_date\" field.")
    updated_at: Optional[StrictStr] = Field(default=None, description="UpdatedAt holds the value of the \"updated_at\" field.")
    __properties: ClassVar[List[str]] = ["cost", "created_at", "date", "description", "edges", "id", "item_id", "name", "scheduled_date", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntMaintenanceEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of edges
        if self.edges:
            _dict['edges'] = self.edges.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntMaintenanceEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cost": obj.get("cost"),
            "created_at": obj.get("created_at"),
            "date": obj.get("date"),
            "description": obj.get("description"),
            "edges": EntMaintenanceEntryEdges.from_dict(obj["edges"]) if obj.get("edges") is not None else None,
            "id": obj.get("id"),
            "item_id": obj.get("item_id"),
            "name": obj.get("name"),
            "scheduled_date": obj.get("scheduled_date"),
            "updated_at": obj.get("updated_at")
        })
        return _obj

from homebox_client.models.ent_maintenance_entry_edges import EntMaintenanceEntryEdges
# TODO: Rewrite to not use raise_errors
EntMaintenanceEntry.model_rebuild(raise_errors=False)

