# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EntUserEdges(BaseModel):
    """
    EntUserEdges
    """ # noqa: E501
    auth_tokens: Optional[List[EntAuthTokens]] = Field(default=None, description="AuthTokens holds the value of the auth_tokens edge.")
    group: Optional[EntGroup] = Field(default=None, description="Group holds the value of the group edge.")
    notifiers: Optional[List[EntNotifier]] = Field(default=None, description="Notifiers holds the value of the notifiers edge.")
    __properties: ClassVar[List[str]] = ["auth_tokens", "group", "notifiers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntUserEdges from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in auth_tokens (list)
        _items = []
        if self.auth_tokens:
            for _item_auth_tokens in self.auth_tokens:
                if _item_auth_tokens:
                    _items.append(_item_auth_tokens.to_dict())
            _dict['auth_tokens'] = _items
        # override the default output from pydantic by calling `to_dict()` of group
        if self.group:
            _dict['group'] = self.group.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in notifiers (list)
        _items = []
        if self.notifiers:
            for _item_notifiers in self.notifiers:
                if _item_notifiers:
                    _items.append(_item_notifiers.to_dict())
            _dict['notifiers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntUserEdges from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auth_tokens": [EntAuthTokens.from_dict(_item) for _item in obj["auth_tokens"]] if obj.get("auth_tokens") is not None else None,
            "group": EntGroup.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "notifiers": [EntNotifier.from_dict(_item) for _item in obj["notifiers"]] if obj.get("notifiers") is not None else None
        })
        return _obj

from homebox_client.models.ent_auth_tokens import EntAuthTokens
from homebox_client.models.ent_group import EntGroup
from homebox_client.models.ent_notifier import EntNotifier
# TODO: Rewrite to not use raise_errors
EntUserEdges.model_rebuild(raise_errors=False)

