# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EntGroupEdges(BaseModel):
    """
    EntGroupEdges
    """ # noqa: E501
    invitation_tokens: Optional[List[EntGroupInvitationToken]] = Field(default=None, description="InvitationTokens holds the value of the invitation_tokens edge.")
    items: Optional[List[EntItem]] = Field(default=None, description="Items holds the value of the items edge.")
    labels: Optional[List[EntLabel]] = Field(default=None, description="Labels holds the value of the labels edge.")
    locations: Optional[List[EntLocation]] = Field(default=None, description="Locations holds the value of the locations edge.")
    notifiers: Optional[List[EntNotifier]] = Field(default=None, description="Notifiers holds the value of the notifiers edge.")
    users: Optional[List[EntUser]] = Field(default=None, description="Users holds the value of the users edge.")
    __properties: ClassVar[List[str]] = ["invitation_tokens", "items", "labels", "locations", "notifiers", "users"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntGroupEdges from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in invitation_tokens (list)
        _items = []
        if self.invitation_tokens:
            for _item_invitation_tokens in self.invitation_tokens:
                if _item_invitation_tokens:
                    _items.append(_item_invitation_tokens.to_dict())
            _dict['invitation_tokens'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in locations (list)
        _items = []
        if self.locations:
            for _item_locations in self.locations:
                if _item_locations:
                    _items.append(_item_locations.to_dict())
            _dict['locations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in notifiers (list)
        _items = []
        if self.notifiers:
            for _item_notifiers in self.notifiers:
                if _item_notifiers:
                    _items.append(_item_notifiers.to_dict())
            _dict['notifiers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in users (list)
        _items = []
        if self.users:
            for _item_users in self.users:
                if _item_users:
                    _items.append(_item_users.to_dict())
            _dict['users'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntGroupEdges from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "invitation_tokens": [EntGroupInvitationToken.from_dict(_item) for _item in obj["invitation_tokens"]] if obj.get("invitation_tokens") is not None else None,
            "items": [EntItem.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "labels": [EntLabel.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "locations": [EntLocation.from_dict(_item) for _item in obj["locations"]] if obj.get("locations") is not None else None,
            "notifiers": [EntNotifier.from_dict(_item) for _item in obj["notifiers"]] if obj.get("notifiers") is not None else None,
            "users": [EntUser.from_dict(_item) for _item in obj["users"]] if obj.get("users") is not None else None
        })
        return _obj

from homebox_client.models.ent_group_invitation_token import EntGroupInvitationToken
from homebox_client.models.ent_item import EntItem
from homebox_client.models.ent_label import EntLabel
from homebox_client.models.ent_location import EntLocation
from homebox_client.models.ent_notifier import EntNotifier
from homebox_client.models.ent_user import EntUser
# TODO: Rewrite to not use raise_errors
EntGroupEdges.model_rebuild(raise_errors=False)

