# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EntLabel(BaseModel):
    """
    EntLabel
    """ # noqa: E501
    color: Optional[StrictStr] = Field(default=None, description="Color holds the value of the \"color\" field.")
    created_at: Optional[StrictStr] = Field(default=None, description="CreatedAt holds the value of the \"created_at\" field.")
    description: Optional[StrictStr] = Field(default=None, description="Description holds the value of the \"description\" field.")
    edges: Optional[EntLabelEdges] = Field(default=None, description="Edges holds the relations/edges for other nodes in the graph. The values are being populated by the LabelQuery when eager-loading is set.")
    id: Optional[StrictStr] = Field(default=None, description="ID of the ent.")
    name: Optional[StrictStr] = Field(default=None, description="Name holds the value of the \"name\" field.")
    updated_at: Optional[StrictStr] = Field(default=None, description="UpdatedAt holds the value of the \"updated_at\" field.")
    __properties: ClassVar[List[str]] = ["color", "created_at", "description", "edges", "id", "name", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntLabel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of edges
        if self.edges:
            _dict['edges'] = self.edges.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntLabel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "color": obj.get("color"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "edges": EntLabelEdges.from_dict(obj["edges"]) if obj.get("edges") is not None else None,
            "id": obj.get("id"),
            "name": obj.get("name"),
            "updated_at": obj.get("updated_at")
        })
        return _obj

from homebox_client.models.ent_label_edges import EntLabelEdges
# TODO: Rewrite to not use raise_errors
EntLabel.model_rebuild(raise_errors=False)

