# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EntNotifier(BaseModel):
    """
    EntNotifier
    """ # noqa: E501
    created_at: Optional[StrictStr] = Field(default=None, description="CreatedAt holds the value of the \"created_at\" field.")
    edges: Optional[EntNotifierEdges] = Field(default=None, description="Edges holds the relations/edges for other nodes in the graph. The values are being populated by the NotifierQuery when eager-loading is set.")
    group_id: Optional[StrictStr] = Field(default=None, description="GroupID holds the value of the \"group_id\" field.")
    id: Optional[StrictStr] = Field(default=None, description="ID of the ent.")
    is_active: Optional[StrictBool] = Field(default=None, description="IsActive holds the value of the \"is_active\" field.")
    name: Optional[StrictStr] = Field(default=None, description="Name holds the value of the \"name\" field.")
    updated_at: Optional[StrictStr] = Field(default=None, description="UpdatedAt holds the value of the \"updated_at\" field.")
    user_id: Optional[StrictStr] = Field(default=None, description="UserID holds the value of the \"user_id\" field.")
    __properties: ClassVar[List[str]] = ["created_at", "edges", "group_id", "id", "is_active", "name", "updated_at", "user_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntNotifier from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of edges
        if self.edges:
            _dict['edges'] = self.edges.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntNotifier from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "edges": EntNotifierEdges.from_dict(obj["edges"]) if obj.get("edges") is not None else None,
            "group_id": obj.get("group_id"),
            "id": obj.get("id"),
            "is_active": obj.get("is_active"),
            "name": obj.get("name"),
            "updated_at": obj.get("updated_at"),
            "user_id": obj.get("user_id")
        })
        return _obj

from homebox_client.models.ent_notifier_edges import EntNotifierEdges
# TODO: Rewrite to not use raise_errors
EntNotifier.model_rebuild(raise_errors=False)

