# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EntItemEdges(BaseModel):
    """
    EntItemEdges
    """ # noqa: E501
    attachments: Optional[List[EntAttachment]] = Field(default=None, description="Attachments holds the value of the attachments edge.")
    children: Optional[List[EntItem]] = Field(default=None, description="Children holds the value of the children edge.")
    fields: Optional[List[EntItemField]] = Field(default=None, description="Fields holds the value of the fields edge.")
    group: Optional[EntGroup] = Field(default=None, description="Group holds the value of the group edge.")
    label: Optional[List[EntLabel]] = Field(default=None, description="Label holds the value of the label edge.")
    location: Optional[EntLocation] = Field(default=None, description="Location holds the value of the location edge.")
    maintenance_entries: Optional[List[EntMaintenanceEntry]] = Field(default=None, description="MaintenanceEntries holds the value of the maintenance_entries edge.")
    parent: Optional[EntItem] = Field(default=None, description="Parent holds the value of the parent edge.")
    __properties: ClassVar[List[str]] = ["attachments", "children", "fields", "group", "label", "location", "maintenance_entries", "parent"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntItemEdges from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                if _item_children:
                    _items.append(_item_children.to_dict())
            _dict['children'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list)
        _items = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items.append(_item_fields.to_dict())
            _dict['fields'] = _items
        # override the default output from pydantic by calling `to_dict()` of group
        if self.group:
            _dict['group'] = self.group.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in label (list)
        _items = []
        if self.label:
            for _item_label in self.label:
                if _item_label:
                    _items.append(_item_label.to_dict())
            _dict['label'] = _items
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in maintenance_entries (list)
        _items = []
        if self.maintenance_entries:
            for _item_maintenance_entries in self.maintenance_entries:
                if _item_maintenance_entries:
                    _items.append(_item_maintenance_entries.to_dict())
            _dict['maintenance_entries'] = _items
        # override the default output from pydantic by calling `to_dict()` of parent
        if self.parent:
            _dict['parent'] = self.parent.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntItemEdges from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attachments": [EntAttachment.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None,
            "children": [EntItem.from_dict(_item) for _item in obj["children"]] if obj.get("children") is not None else None,
            "fields": [EntItemField.from_dict(_item) for _item in obj["fields"]] if obj.get("fields") is not None else None,
            "group": EntGroup.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "label": [EntLabel.from_dict(_item) for _item in obj["label"]] if obj.get("label") is not None else None,
            "location": EntLocation.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "maintenance_entries": [EntMaintenanceEntry.from_dict(_item) for _item in obj["maintenance_entries"]] if obj.get("maintenance_entries") is not None else None,
            "parent": EntItem.from_dict(obj["parent"]) if obj.get("parent") is not None else None
        })
        return _obj

from homebox_client.models.ent_attachment import EntAttachment
from homebox_client.models.ent_group import EntGroup
from homebox_client.models.ent_item import EntItem
from homebox_client.models.ent_item_field import EntItemField
from homebox_client.models.ent_label import EntLabel
from homebox_client.models.ent_location import EntLocation
from homebox_client.models.ent_maintenance_entry import EntMaintenanceEntry
# TODO: Rewrite to not use raise_errors
EntItemEdges.model_rebuild(raise_errors=False)

