# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from homebox_client.models.itemfield_type import ItemfieldType
from typing import Optional, Set
from typing_extensions import Self

class EntItemField(BaseModel):
    """
    EntItemField
    """ # noqa: E501
    boolean_value: Optional[StrictBool] = Field(default=None, description="BooleanValue holds the value of the \"boolean_value\" field.")
    created_at: Optional[StrictStr] = Field(default=None, description="CreatedAt holds the value of the \"created_at\" field.")
    description: Optional[StrictStr] = Field(default=None, description="Description holds the value of the \"description\" field.")
    edges: Optional[EntItemFieldEdges] = Field(default=None, description="Edges holds the relations/edges for other nodes in the graph. The values are being populated by the ItemFieldQuery when eager-loading is set.")
    id: Optional[StrictStr] = Field(default=None, description="ID of the ent.")
    name: Optional[StrictStr] = Field(default=None, description="Name holds the value of the \"name\" field.")
    number_value: Optional[StrictInt] = Field(default=None, description="NumberValue holds the value of the \"number_value\" field.")
    text_value: Optional[StrictStr] = Field(default=None, description="TextValue holds the value of the \"text_value\" field.")
    time_value: Optional[StrictStr] = Field(default=None, description="TimeValue holds the value of the \"time_value\" field.")
    type: Optional[ItemfieldType] = Field(default=None, description="Type holds the value of the \"type\" field.")
    updated_at: Optional[StrictStr] = Field(default=None, description="UpdatedAt holds the value of the \"updated_at\" field.")
    __properties: ClassVar[List[str]] = ["boolean_value", "created_at", "description", "edges", "id", "name", "number_value", "text_value", "time_value", "type", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntItemField from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of edges
        if self.edges:
            _dict['edges'] = self.edges.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntItemField from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "boolean_value": obj.get("boolean_value"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "edges": EntItemFieldEdges.from_dict(obj["edges"]) if obj.get("edges") is not None else None,
            "id": obj.get("id"),
            "name": obj.get("name"),
            "number_value": obj.get("number_value"),
            "text_value": obj.get("text_value"),
            "time_value": obj.get("time_value"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at")
        })
        return _obj

from homebox_client.models.ent_item_field_edges import EntItemFieldEdges
# TODO: Rewrite to not use raise_errors
EntItemField.model_rebuild(raise_errors=False)

