# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class EntItem(BaseModel):
    """
    EntItem
    """ # noqa: E501
    archived: Optional[StrictBool] = Field(default=None, description="Archived holds the value of the \"archived\" field.")
    asset_id: Optional[StrictInt] = Field(default=None, description="AssetID holds the value of the \"asset_id\" field.")
    created_at: Optional[StrictStr] = Field(default=None, description="CreatedAt holds the value of the \"created_at\" field.")
    description: Optional[StrictStr] = Field(default=None, description="Description holds the value of the \"description\" field.")
    edges: Optional[EntItemEdges] = Field(default=None, description="Edges holds the relations/edges for other nodes in the graph. The values are being populated by the ItemQuery when eager-loading is set.")
    id: Optional[StrictStr] = Field(default=None, description="ID of the ent.")
    import_ref: Optional[StrictStr] = Field(default=None, description="ImportRef holds the value of the \"import_ref\" field.")
    insured: Optional[StrictBool] = Field(default=None, description="Insured holds the value of the \"insured\" field.")
    lifetime_warranty: Optional[StrictBool] = Field(default=None, description="LifetimeWarranty holds the value of the \"lifetime_warranty\" field.")
    manufacturer: Optional[StrictStr] = Field(default=None, description="Manufacturer holds the value of the \"manufacturer\" field.")
    model_number: Optional[StrictStr] = Field(default=None, description="ModelNumber holds the value of the \"model_number\" field.")
    name: Optional[StrictStr] = Field(default=None, description="Name holds the value of the \"name\" field.")
    notes: Optional[StrictStr] = Field(default=None, description="Notes holds the value of the \"notes\" field.")
    purchase_from: Optional[StrictStr] = Field(default=None, description="PurchaseFrom holds the value of the \"purchase_from\" field.")
    purchase_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="PurchasePrice holds the value of the \"purchase_price\" field.")
    purchase_time: Optional[StrictStr] = Field(default=None, description="PurchaseTime holds the value of the \"purchase_time\" field.")
    quantity: Optional[StrictInt] = Field(default=None, description="Quantity holds the value of the \"quantity\" field.")
    serial_number: Optional[StrictStr] = Field(default=None, description="SerialNumber holds the value of the \"serial_number\" field.")
    sold_notes: Optional[StrictStr] = Field(default=None, description="SoldNotes holds the value of the \"sold_notes\" field.")
    sold_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="SoldPrice holds the value of the \"sold_price\" field.")
    sold_time: Optional[StrictStr] = Field(default=None, description="SoldTime holds the value of the \"sold_time\" field.")
    sold_to: Optional[StrictStr] = Field(default=None, description="SoldTo holds the value of the \"sold_to\" field.")
    sync_child_items_locations: Optional[StrictBool] = Field(default=None, description="SyncChildItemsLocations holds the value of the \"sync_child_items_locations\" field.")
    updated_at: Optional[StrictStr] = Field(default=None, description="UpdatedAt holds the value of the \"updated_at\" field.")
    warranty_details: Optional[StrictStr] = Field(default=None, description="WarrantyDetails holds the value of the \"warranty_details\" field.")
    warranty_expires: Optional[StrictStr] = Field(default=None, description="WarrantyExpires holds the value of the \"warranty_expires\" field.")
    __properties: ClassVar[List[str]] = ["archived", "asset_id", "created_at", "description", "edges", "id", "import_ref", "insured", "lifetime_warranty", "manufacturer", "model_number", "name", "notes", "purchase_from", "purchase_price", "purchase_time", "quantity", "serial_number", "sold_notes", "sold_price", "sold_time", "sold_to", "sync_child_items_locations", "updated_at", "warranty_details", "warranty_expires"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of edges
        if self.edges:
            _dict['edges'] = self.edges.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "archived": obj.get("archived"),
            "asset_id": obj.get("asset_id"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "edges": EntItemEdges.from_dict(obj["edges"]) if obj.get("edges") is not None else None,
            "id": obj.get("id"),
            "import_ref": obj.get("import_ref"),
            "insured": obj.get("insured"),
            "lifetime_warranty": obj.get("lifetime_warranty"),
            "manufacturer": obj.get("manufacturer"),
            "model_number": obj.get("model_number"),
            "name": obj.get("name"),
            "notes": obj.get("notes"),
            "purchase_from": obj.get("purchase_from"),
            "purchase_price": obj.get("purchase_price"),
            "purchase_time": obj.get("purchase_time"),
            "quantity": obj.get("quantity"),
            "serial_number": obj.get("serial_number"),
            "sold_notes": obj.get("sold_notes"),
            "sold_price": obj.get("sold_price"),
            "sold_time": obj.get("sold_time"),
            "sold_to": obj.get("sold_to"),
            "sync_child_items_locations": obj.get("sync_child_items_locations"),
            "updated_at": obj.get("updated_at"),
            "warranty_details": obj.get("warranty_details"),
            "warranty_expires": obj.get("warranty_expires")
        })
        return _obj

from homebox_client.models.ent_item_edges import EntItemEdges
# TODO: Rewrite to not use raise_errors
EntItem.model_rebuild(raise_errors=False)

