# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EntLocationEdges(BaseModel):
    """
    EntLocationEdges
    """ # noqa: E501
    children: Optional[List[EntLocation]] = Field(default=None, description="Children holds the value of the children edge.")
    group: Optional[EntGroup] = Field(default=None, description="Group holds the value of the group edge.")
    items: Optional[List[EntItem]] = Field(default=None, description="Items holds the value of the items edge.")
    parent: Optional[EntLocation] = Field(default=None, description="Parent holds the value of the parent edge.")
    __properties: ClassVar[List[str]] = ["children", "group", "items", "parent"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntLocationEdges from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                if _item_children:
                    _items.append(_item_children.to_dict())
            _dict['children'] = _items
        # override the default output from pydantic by calling `to_dict()` of group
        if self.group:
            _dict['group'] = self.group.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of parent
        if self.parent:
            _dict['parent'] = self.parent.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntLocationEdges from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "children": [EntLocation.from_dict(_item) for _item in obj["children"]] if obj.get("children") is not None else None,
            "group": EntGroup.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "items": [EntItem.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "parent": EntLocation.from_dict(obj["parent"]) if obj.get("parent") is not None else None
        })
        return _obj

from homebox_client.models.ent_group import EntGroup
from homebox_client.models.ent_item import EntItem
from homebox_client.models.ent_location import EntLocation
# TODO: Rewrite to not use raise_errors
EntLocationEdges.model_rebuild(raise_errors=False)

