# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from homebox_client.models.repo_item_attachment import RepoItemAttachment
from homebox_client.models.repo_item_field import RepoItemField
from homebox_client.models.repo_item_summary import RepoItemSummary
from homebox_client.models.repo_label_summary import RepoLabelSummary
from homebox_client.models.repo_location_summary import RepoLocationSummary
from typing import Optional, Set
from typing_extensions import Self

class RepoItemOut(BaseModel):
    """
    RepoItemOut
    """ # noqa: E501
    archived: Optional[StrictBool] = None
    asset_id: Optional[StrictStr] = Field(default=None, alias="assetId")
    attachments: Optional[List[RepoItemAttachment]] = None
    created_at: Optional[StrictStr] = Field(default=None, alias="createdAt")
    description: Optional[StrictStr] = None
    fields: Optional[List[RepoItemField]] = None
    id: Optional[StrictStr] = None
    image_id: Optional[StrictStr] = Field(default=None, alias="imageId")
    insured: Optional[StrictBool] = None
    labels: Optional[List[RepoLabelSummary]] = None
    lifetime_warranty: Optional[StrictBool] = Field(default=None, description="Warranty", alias="lifetimeWarranty")
    location: Optional[RepoLocationSummary] = Field(default=None, description="Edges")
    manufacturer: Optional[StrictStr] = None
    model_number: Optional[StrictStr] = Field(default=None, alias="modelNumber")
    name: Optional[StrictStr] = None
    notes: Optional[StrictStr] = Field(default=None, description="Extras")
    parent: Optional[RepoItemSummary] = None
    purchase_from: Optional[StrictStr] = Field(default=None, alias="purchaseFrom")
    purchase_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="purchasePrice")
    purchase_time: Optional[StrictStr] = Field(default=None, description="Purchase", alias="purchaseTime")
    quantity: Optional[StrictInt] = None
    serial_number: Optional[StrictStr] = Field(default=None, alias="serialNumber")
    sold_notes: Optional[StrictStr] = Field(default=None, alias="soldNotes")
    sold_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="soldPrice")
    sold_time: Optional[StrictStr] = Field(default=None, description="Sold", alias="soldTime")
    sold_to: Optional[StrictStr] = Field(default=None, alias="soldTo")
    sync_child_items_locations: Optional[StrictBool] = Field(default=None, alias="syncChildItemsLocations")
    thumbnail_id: Optional[StrictStr] = Field(default=None, alias="thumbnailId")
    updated_at: Optional[StrictStr] = Field(default=None, alias="updatedAt")
    warranty_details: Optional[StrictStr] = Field(default=None, alias="warrantyDetails")
    warranty_expires: Optional[StrictStr] = Field(default=None, alias="warrantyExpires")
    __properties: ClassVar[List[str]] = ["archived", "assetId", "attachments", "createdAt", "description", "fields", "id", "imageId", "insured", "labels", "lifetimeWarranty", "location", "manufacturer", "modelNumber", "name", "notes", "parent", "purchaseFrom", "purchasePrice", "purchaseTime", "quantity", "serialNumber", "soldNotes", "soldPrice", "soldTime", "soldTo", "syncChildItemsLocations", "thumbnailId", "updatedAt", "warrantyDetails", "warrantyExpires"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RepoItemOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list)
        _items = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items.append(_item_fields.to_dict())
            _dict['fields'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of parent
        if self.parent:
            _dict['parent'] = self.parent.to_dict()
        # set to None if image_id (nullable) is None
        # and model_fields_set contains the field
        if self.image_id is None and "image_id" in self.model_fields_set:
            _dict['imageId'] = None

        # set to None if location (nullable) is None
        # and model_fields_set contains the field
        if self.location is None and "location" in self.model_fields_set:
            _dict['location'] = None

        # set to None if parent (nullable) is None
        # and model_fields_set contains the field
        if self.parent is None and "parent" in self.model_fields_set:
            _dict['parent'] = None

        # set to None if thumbnail_id (nullable) is None
        # and model_fields_set contains the field
        if self.thumbnail_id is None and "thumbnail_id" in self.model_fields_set:
            _dict['thumbnailId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RepoItemOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "archived": obj.get("archived"),
            "assetId": obj.get("assetId"),
            "attachments": [RepoItemAttachment.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None,
            "createdAt": obj.get("createdAt"),
            "description": obj.get("description"),
            "fields": [RepoItemField.from_dict(_item) for _item in obj["fields"]] if obj.get("fields") is not None else None,
            "id": obj.get("id"),
            "imageId": obj.get("imageId"),
            "insured": obj.get("insured"),
            "labels": [RepoLabelSummary.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "lifetimeWarranty": obj.get("lifetimeWarranty"),
            "location": RepoLocationSummary.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "manufacturer": obj.get("manufacturer"),
            "modelNumber": obj.get("modelNumber"),
            "name": obj.get("name"),
            "notes": obj.get("notes"),
            "parent": RepoItemSummary.from_dict(obj["parent"]) if obj.get("parent") is not None else None,
            "purchaseFrom": obj.get("purchaseFrom"),
            "purchasePrice": obj.get("purchasePrice"),
            "purchaseTime": obj.get("purchaseTime"),
            "quantity": obj.get("quantity"),
            "serialNumber": obj.get("serialNumber"),
            "soldNotes": obj.get("soldNotes"),
            "soldPrice": obj.get("soldPrice"),
            "soldTime": obj.get("soldTime"),
            "soldTo": obj.get("soldTo"),
            "syncChildItemsLocations": obj.get("syncChildItemsLocations"),
            "thumbnailId": obj.get("thumbnailId"),
            "updatedAt": obj.get("updatedAt"),
            "warrantyDetails": obj.get("warrantyDetails"),
            "warrantyExpires": obj.get("warrantyExpires")
        })
        return _obj


