# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from homebox_client.models.repo_item_create import RepoItemCreate
from typing import Optional, Set
from typing_extensions import Self

class RepoBarcodeProduct(BaseModel):
    """
    RepoBarcodeProduct
    """ # noqa: E501
    barcode: Optional[StrictStr] = None
    image_base64: Optional[StrictStr] = Field(default=None, alias="imageBase64")
    image_url: Optional[StrictStr] = Field(default=None, alias="imageURL")
    item: Optional[RepoItemCreate] = None
    manufacturer: Optional[StrictStr] = None
    model_number: Optional[StrictStr] = Field(default=None, description="Identifications", alias="modelNumber")
    notes: Optional[StrictStr] = Field(default=None, description="Extras")
    search_engine_name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["barcode", "imageBase64", "imageURL", "item", "manufacturer", "modelNumber", "notes", "search_engine_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RepoBarcodeProduct from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of item
        if self.item:
            _dict['item'] = self.item.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RepoBarcodeProduct from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "barcode": obj.get("barcode"),
            "imageBase64": obj.get("imageBase64"),
            "imageURL": obj.get("imageURL"),
            "item": RepoItemCreate.from_dict(obj["item"]) if obj.get("item") is not None else None,
            "manufacturer": obj.get("manufacturer"),
            "modelNumber": obj.get("modelNumber"),
            "notes": obj.get("notes"),
            "search_engine_name": obj.get("search_engine_name")
        })
        return _obj


