# coding: utf-8

"""
    Homebox API

    Track, Manage, and Organize your Things.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from homebox_client.models.repo_item_field import RepoItemField
from typing import Optional, Set
from typing_extensions import Self

class RepoItemUpdate(BaseModel):
    """
    RepoItemUpdate
    """ # noqa: E501
    archived: Optional[StrictBool] = None
    asset_id: Optional[StrictStr] = Field(default=None, alias="assetId")
    description: Optional[Annotated[str, Field(strict=True, max_length=1000)]] = None
    fields: Optional[List[RepoItemField]] = None
    id: Optional[StrictStr] = None
    insured: Optional[StrictBool] = None
    label_ids: Optional[List[StrictStr]] = Field(default=None, alias="labelIds")
    lifetime_warranty: Optional[StrictBool] = Field(default=None, description="Warranty", alias="lifetimeWarranty")
    location_id: Optional[StrictStr] = Field(default=None, description="Edges", alias="locationId")
    manufacturer: Optional[StrictStr] = None
    model_number: Optional[StrictStr] = Field(default=None, alias="modelNumber")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    notes: Optional[StrictStr] = Field(default=None, description="Extras")
    parent_id: Optional[StrictStr] = Field(default=None, alias="parentId")
    purchase_from: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, alias="purchaseFrom")
    purchase_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="purchasePrice")
    purchase_time: Optional[StrictStr] = Field(default=None, description="Purchase", alias="purchaseTime")
    quantity: Optional[StrictInt] = None
    serial_number: Optional[StrictStr] = Field(default=None, description="Identifications", alias="serialNumber")
    sold_notes: Optional[StrictStr] = Field(default=None, alias="soldNotes")
    sold_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="soldPrice")
    sold_time: Optional[StrictStr] = Field(default=None, description="Sold", alias="soldTime")
    sold_to: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, alias="soldTo")
    sync_child_items_locations: Optional[StrictBool] = Field(default=None, alias="syncChildItemsLocations")
    warranty_details: Optional[StrictStr] = Field(default=None, alias="warrantyDetails")
    warranty_expires: Optional[StrictStr] = Field(default=None, alias="warrantyExpires")
    __properties: ClassVar[List[str]] = ["archived", "assetId", "description", "fields", "id", "insured", "labelIds", "lifetimeWarranty", "locationId", "manufacturer", "modelNumber", "name", "notes", "parentId", "purchaseFrom", "purchasePrice", "purchaseTime", "quantity", "serialNumber", "soldNotes", "soldPrice", "soldTime", "soldTo", "syncChildItemsLocations", "warrantyDetails", "warrantyExpires"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RepoItemUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list)
        _items = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items.append(_item_fields.to_dict())
            _dict['fields'] = _items
        # set to None if parent_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_id is None and "parent_id" in self.model_fields_set:
            _dict['parentId'] = None

        # set to None if purchase_price (nullable) is None
        # and model_fields_set contains the field
        if self.purchase_price is None and "purchase_price" in self.model_fields_set:
            _dict['purchasePrice'] = None

        # set to None if sold_price (nullable) is None
        # and model_fields_set contains the field
        if self.sold_price is None and "sold_price" in self.model_fields_set:
            _dict['soldPrice'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RepoItemUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "archived": obj.get("archived"),
            "assetId": obj.get("assetId"),
            "description": obj.get("description"),
            "fields": [RepoItemField.from_dict(_item) for _item in obj["fields"]] if obj.get("fields") is not None else None,
            "id": obj.get("id"),
            "insured": obj.get("insured"),
            "labelIds": obj.get("labelIds"),
            "lifetimeWarranty": obj.get("lifetimeWarranty"),
            "locationId": obj.get("locationId"),
            "manufacturer": obj.get("manufacturer"),
            "modelNumber": obj.get("modelNumber"),
            "name": obj.get("name"),
            "notes": obj.get("notes"),
            "parentId": obj.get("parentId"),
            "purchaseFrom": obj.get("purchaseFrom"),
            "purchasePrice": obj.get("purchasePrice"),
            "purchaseTime": obj.get("purchaseTime"),
            "quantity": obj.get("quantity"),
            "serialNumber": obj.get("serialNumber"),
            "soldNotes": obj.get("soldNotes"),
            "soldPrice": obj.get("soldPrice"),
            "soldTime": obj.get("soldTime"),
            "soldTo": obj.get("soldTo"),
            "syncChildItemsLocations": obj.get("syncChildItemsLocations"),
            "warrantyDetails": obj.get("warrantyDetails"),
            "warrantyExpires": obj.get("warrantyExpires")
        })
        return _obj


